import { useEffect, useState } from "react";
import api from "../services/api";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function Reports() {
  const [complaints, setComplaints] = useState([]);

  useEffect(() => {
    fetchComplaints();
  }, []);

  const fetchComplaints = async () => {
    try {
      const response = await api.get("complaints/complaints/");

      const data = Array.isArray(response.data)
        ? response.data
        : response.data.results || [];

      setComplaints(data);
    } catch (error) {
      console.error(error);
    }
  };

  const exportExcel = () => {
  const workbook = XLSX.utils.book_new();

  const rows = [];

  // Company Header
  rows.push(["INDIAN OIL CORPORATION LIMITED"]);
  rows.push(["Smart Complaint Management System"]);
  rows.push([]);

  rows.push(["Complaint Report"]);
  rows.push([
    "Generated:",
    new Date().toLocaleString(),
  ]);

  rows.push([]);

  const open = complaints.filter(
    (c) => c.status === "OPEN"
  ).length;

  const assigned = complaints.filter(
    (c) => c.status === "ASSIGNED"
  ).length;

  const progress = complaints.filter(
    (c) => c.status === "IN_PROGRESS"
  ).length;

  const resolved = complaints.filter(
    (c) => c.status === "RESOLVED"
  ).length;

  rows.push(["Total Complaints", complaints.length]);
  rows.push(["Open", open]);
  rows.push(["Assigned", assigned]);
  rows.push(["In Progress", progress]);
  rows.push(["Resolved", resolved]);

  rows.push([]);

  rows.push([
    "Complaint ID",
    "Title",
    "Category",
    "Priority",
    "Status",
    "Created At",
  ]);

  complaints.forEach((c) => {
    rows.push([
      c.complaint_id,
      c.title,
      c.category,
      c.priority,
      c.status,
      c.created_at,
    ]);
  });

  const worksheet =
    XLSX.utils.aoa_to_sheet(rows);

  worksheet["!cols"] = [
    { wch: 22 },
    { wch: 28 },
    { wch: 18 },
    { wch: 15 },
    { wch: 18 },
    { wch: 28 },
  ];

  worksheet["!freeze"] = {
    xSplit: 0,
    ySplit: 12,
  };

  XLSX.utils.book_append_sheet(
    workbook,
    worksheet,
    "Complaint Report"
  );

  XLSX.writeFile(
    workbook,
    `IOCL_Complaint_Report_${
      new Date().toISOString().split("T")[0]
    }.xlsx`
  );
};

  const exportPDF = () => {
    const doc = new jsPDF();

   const open = complaints.filter(
  (c) => c.status === "OPEN"
).length;

const assigned = complaints.filter(
  (c) => c.status === "ASSIGNED"
).length;

const progress = complaints.filter(
  (c) => c.status === "IN_PROGRESS"
).length;

const resolved = complaints.filter(
  (c) => c.status === "RESOLVED"
).length;

    // Header
    doc.setFillColor(0, 24, 69);
    doc.rect(0, 0, 210, 28, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text("Indian Oil Corporation Limited", 14, 15);

    doc.setFontSize(11);
    doc.text(
      "Smart Complaint Management System",
      14,
      22
    );

    // Report Title
    doc.setTextColor(0);

    doc.setFontSize(18);
    doc.text("Complaint Report", 14, 40);

    doc.setFontSize(10);

    doc.text(
      "Generated : " +
        new Date().toLocaleString(),
      14,
      47
    );

    // Summary Box

    doc.setDrawColor(200);

    doc.roundedRect(14, 55, 182, 24, 3, 3);

    doc.setFontSize(12);

    doc.text(
      `Total Complaints : ${complaints.length}`,
      18,
      64
    );

    doc.text(
  `Open : ${open}`,
  18,
  64
);

doc.text(
  `Assigned : ${assigned}`,
  70,
  64
);

doc.text(
  `In Progress : ${progress}`,
  120,
  64
);

doc.text(
  `Resolved : ${resolved}`,
  18,
  72
);

    autoTable(doc, {
      startY: 88,

      head: [[
        "ID",
        "Title",
        "Category",
        "Priority",
        "Status",
      ]],

      body: complaints.map((c) => [
        c.complaint_id,
        c.title,
        c.category,
        c.priority,
        c.status,
      ]),

      headStyles: {
        fillColor: [0, 24, 69],
      },

      styles: {
        fontSize: 10,
      },

      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },
    });

    doc.setFontSize(10);

    doc.text(
      "Generated by IOCL Smart Complaint Management System",
      14,
      doc.lastAutoTable.finalY + 15
    );

    doc.save("IOCL_Complaint_Report.pdf");
  };

  return (
    <div>
      <h1
        style={{
          fontSize: "42px",
          fontWeight: "700",
          color: "#0f172a",
          marginBottom: "10px",
        }}
      >
        Reports Center
      </h1>

      <p
        style={{
          color: "#64748b",
          marginBottom: "30px",
        }}
      >
        Generate professional complaint reports.
      </p>

      <div
        style={{
          display: "flex",
          gap: "20px",
          marginBottom: "30px",
        }}
      >
        <button
          onClick={exportExcel}
          style={{
            background: "#2563eb",
            color: "white",
            border: "none",
            padding: "14px 24px",
            borderRadius: "12px",
            cursor: "pointer",
            fontWeight: "600",
          }}
        >
          📊 Export Excel
        </button>

        <button
          onClick={exportPDF}
          style={{
            background: "#16a34a",
            color: "white",
            border: "none",
            padding: "14px 24px",
            borderRadius: "12px",
            cursor: "pointer",
            fontWeight: "600",
          }}
        >
          📄 Export Professional PDF
        </button>
      </div>

      <div
        style={{
          background: "white",
          borderRadius: "20px",
          padding: "25px",
          boxShadow:
            "0 10px 30px rgba(15,23,42,0.08)",
        }}
      >
        <h2>Report Summary</h2>

        <h3>Total Complaints : {complaints.length}</h3>

        <p>
  Open :
  {
    complaints.filter(
      (c) => c.status === "OPEN"
    ).length
  }
</p>

<p>
  Assigned :
  {
    complaints.filter(
      (c) => c.status === "ASSIGNED"
    ).length
  }
</p>

<p>
  In Progress :
  {
    complaints.filter(
      (c) => c.status === "IN_PROGRESS"
    ).length
  }
</p>

<p>
  Resolved :
  {
    complaints.filter(
      (c) => c.status === "RESOLVED"
    ).length
}
</p>
      </div>
    </div>
  );
}

export default Reports;